// Generated by Apple Swift version 1.2 (swiftlang-602.0.49.6 clang-602.0.49)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import WebKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class WSSWKWebView;

SWIFT_PROTOCOL("_TtP15WhiteSkyCoreSdk30WSSBrowserLoginServiceDelegate_")
@protocol WSSBrowserLoginServiceDelegate <NSObject>
@optional
- (void)webView:(WSSWKWebView * __nonnull)wssWkWebView loginAvailable:(NSDictionary * __nullable)parameters;
- (void)webView:(WSSWKWebView * __nonnull)wssWkWebView loginExecuted:(NSDictionary * __nullable)parameters;
- (void)webView:(WSSWKWebView * __nonnull)wssWkWebView recordData:(NSDictionary * __nullable)parameters;
- (BOOL)shouldConfirmRecording;
@end


SWIFT_CLASS("_TtC15WhiteSkyCoreSdk16WSSNewtonManager")
@interface WSSNewtonManager : NSObject
+ (WSSNewtonManager * __nonnull)sharedInstance;
- (void)newtonLoginScript:(NSString * __nonnull)urlStr completionHandler:(void (^ __nullable)(BOOL, NSString * __nullable))completionHandler;
@end


SWIFT_PROTOCOL("_TtP15WhiteSkyCoreSdk29WSSRecordLoginConfirmDelegate_")
@protocol WSSRecordLoginConfirmDelegate <NSObject>
@optional
- (void)recordLoginOkTapped;
- (void)recordLoginCancelTapped;
- (void)recordLoginDialogueClose;
@end


SWIFT_CLASS("_TtC15WhiteSkyCoreSdk19WSSWKBrowserToolBar")
@interface WSSWKBrowserToolBar : NSObject
- (void)setAddressBarText:(NSString * __nullable)urlStr;
- (void)setProgress:(float)progress animated:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * __nonnull)keyPath ofObject:(id __nonnull)object change:(NSDictionary * __nonnull)change context:(void * __null_unspecified)context;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC15WhiteSkyCoreSdk26WSSWKBrowserViewController")
@interface WSSWKBrowserViewController : UIViewController <WKNavigationDelegate, WSSBrowserLoginServiceDelegate>
@property (nonatomic) WSSWKWebView * __null_unspecified wssWkWebView;
@property (nonatomic) WSSWKBrowserToolBar * __null_unspecified browserToolbar;
- (void)viewDidLoad;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (void)configureSecureView;
- (void)configureOpenView;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotate;
- (void)viewDidLayoutSubviews;
- (void)loadBrowserWithUrl:(NSString * __nullable)urlToLoad;
- (void)loadBrowserWithUrl:(NSString * __nullable)urlToLoad loginScript:(NSString * __nullable)loginScript;
- (void)loginPlayback:(NSDictionary * __nonnull)loginCredentials;
- (void)showRecordSuccessfulDialogue:(NSString * __nonnull)instructionText closeTimeInSecs:(double)closeTimeInSecs;
- (void)webView:(WKWebView * __nonnull)webView didStartProvisionalNavigation:(WKNavigation * __null_unspecified)navigation;
- (void)webView:(WKWebView * __nonnull)webView didFinishNavigation:(WKNavigation * __null_unspecified)navigation;
- (void)webView:(WKWebView * __nonnull)webView didReceiveServerRedirectForProvisionalNavigation:(WKNavigation * __null_unspecified)navigation;
- (void)toolbarNavigationDoneTapped;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP15WhiteSkyCoreSdk28WSSWKNavigationEventDelegate_")
@protocol WSSWKNavigationEventDelegate <WKNavigationDelegate>
@end

@class WKWebViewConfiguration;
@class NSURLRequest;

SWIFT_CLASS("_TtC15WhiteSkyCoreSdk12WSSWKWebView")
@interface WSSWKWebView : WKWebView
@property (nonatomic) BOOL enhancedMode;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * __nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (WKNavigation * __nullable)loadRequest:(NSURLRequest * __nonnull)request loginScript:(NSString * __nullable)loginScript;
- (WKNavigation * __nullable)loadRequest:(NSURLRequest * __nonnull)request;
- (WKNavigation * __nullable)loadFromUrlString:(NSString * __nullable)urlStr loginScript:(NSString * __nullable)loginScript;
- (WKNavigation * __nullable)loadFromUrlString:(NSString * __nullable)urlStr;
@end


@interface WSSWKWebView (SWIFT_EXTENSION(WhiteSkyCoreSdk))
- (void)injectCoreJs;
- (void)injectLoginJs:(NSString * __nonnull)loginJs;
- (void)initCoreJsScriptHandler;
- (void)removeAllUserScripts;
- (void)removeScriptMessageHandlerForName:(NSString * __nonnull)callbackName;
- (void)fillFields:(NSDictionary * __nonnull)user creditCard:(NSDictionary * __nonnull)creditCard billingAddress:(NSDictionary * __nonnull)billingAddress shippingAddress:(NSDictionary * __nonnull)shippingAddress completionHandler:(void (^ __nonnull)(id __nullable))completionHandler;
@end

#pragma clang diagnostic pop
